FROM golang as builder
WORKDIR /go/src/github.com/gcash/bchd
ADD go.mod .
ADD go.sum .
RUN go mod download
ADD . /go/src/github.com/gcash/bchd
RUN go build -o /opt/bchd .

# Final stage
FROM gcr.io/distroless/base
EXPOSE 8333
VOLUME ["/data"]
ENTRYPOINT ["/opt/bchd", "--addrindex", "--txindex", "-b", "/data", "-C", "/data/bchd.conf"]
COPY --from=builder /opt/bchd /opt/bchd
