apiVersion: v1
kind: Service
metadata:
  name: bchd
  namespace: default
spec:
  ports:
    - name: protocol
      port: 8333
      targetPort: 8333
    - name: prometheus
      port: 9000
      targetPort: 9000
  selector:
    service: bchd
  type: LoadBalancer
  externalTrafficPolicy: Local
